version: '3.8'

services:
  openwrt-router:
    image: maxskokov/nixos-openwrt-luci:24.10
    container_name: devops-router
    network_mode: host
    privileged: true
    tty: true
    restart: always
